//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public string Login { get; set; }
        public System.DateTime Time { get; set; }
        public System.DateTime EntryTime { get; set; }
        public System.DateTime OutTime { get; set; }
        public string LogoutReason { get; set; }
        public int ID { get; set; }
    }
}
